name: Convert Markdown to PDF

on:
  push:
    paths:
      - '**/*.md'  # Only run when .md files are changed
  pull_request:
    paths:
      - '**/*.md'  # Also run on pull requests when .md files are changed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Cache texlive and pandoc
      uses: actions/cache@v3
      with:
        path: |
          /usr/local/bin/pandoc
          $HOME/texlive              # Custom directory for texlive installation
        key: texlive-pandoc-${{ runner.os }}-${{ hashFiles('**/*.md') }}
        restore-keys: |
          texlive-pandoc-${{ runner.os }}-

    - name: Install pandoc and texlive (if cache miss)
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        sudo apt-get update && \
        sudo apt-get install pandoc -y && \
        mkdir -p $HOME/texlive && \
        sudo apt-get install texlive-xetex -y --install-dir=$HOME/texlive

    - name: Convert Markdown files to PDF
      run: |
        mkdir -p output_pdf
        for file in *.md; do
          echo "Converting $file to PDF using xelatex"
          pandoc "$file" -o "output_pdf/${file%.md}.pdf" --pdf-engine=xelatex
        done

    - name: Upload PDF Files
      uses: actions/upload-artifact@v3
      with:
        name: PDFs
        path: output_pdf
