name: Convert Markdown to PDFs

on:
  push:
    paths:
      - '**/*.md'

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Create output directory
        run: mkdir -p output  # Create output directory for PDFs

      - name: Convert each markdown file to PDF
        run: |
          # Find all .md files in the repository (recursive)
          find . -name "*.md" | while read file; do
            filename=$(basename "$file" .md)
            docker run --rm \
              -v "$PWD:/data" \
              pandoc/latex:2.9 \
              -f markdown \
              --pdf-engine=xelatex \
              "/data/$file" -o "/data/output/${filename}.pdf"
          done

      - name: Upload PDFs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: PDFs
          path: output
