name: Convert Markdown to PDF

on:
  push:
    paths:
      - '**/*.md'  # Only run when .md files are changed
  pull_request:
    paths:
      - '**/*.md'  # Also run on pull requests when .md files are changed

jobs:
  build:
    runs-on: ubuntu-latest  # The environment the workflow runs in

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Use the latest version of actions/checkout

    - name: Cache APT lists (restore)
      id: apt-cache-restore
      run: |
        if [[ -f apt-cache.tar ]]; then
          sudo tar -xf apt-cache.tar -C /
        else
          echo "No cache found."
        fi

    - name: Install required packages
      run: |
        sudo apt-get update && \
        sudo apt-get install -y pandoc texlive-xetex  # Install pandoc and texlive

    - name: Convert Markdown files to PDF
      run: |
        mkdir -p output_pdf  # Create output directory for PDFs
        for file in *.md; do
          echo "Converting $file to PDF using xelatex"  # Log the file being processed
          pandoc "$file" -o "output_pdf/${file%.md}.pdf" --pdf-engine=xelatex  # Convert .md to .pdf
        done

    - name: Upload PDF Files
      uses: actions/upload-artifact@v4  # Upload the generated PDFs as artifacts
      with:
        name: PDFs
        path: output_pdf  # Upload the generated PDFs as artifacts

    - name: Cache APT lists (save)
      if: always()
      run: |
        # Exclude problematic directories
        sudo tar --exclude='./partial' --exclude='./lock' -czf apt-cache.tar -C /var/lib/apt/lists .
      continue-on-error: true

    - name: Upload cache tarball
      uses: actions/upload-artifact@v4
      with:
        name: apt-cache
        path: apt-cache.tar
