name: Convert Markdown to PDFs

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Create output directory
        run: mkdir output  # Create output directory for PDFs

      - name: Convert each markdown file to PDF
        run: |
          for file in *.md; do
            filename=$(basename "$file" .md)
            docker run --rm \
              -v "$PWD:/data" \
              pandoc/latex:2.9 \
              "/data/$file" -o "/data/output/${filename}.pdf"
          done

      - name: Upload PDFs as artifact
        uses: actions/upload-artifact@v3
        with:
          name: PDFs
          path: output
