name: Convert Markdown to PDF

on:
  push:
    paths:
      - '**/*.md'  # Only run when .md files are changed
  pull_request:
    paths:
      - '**/*.md'  # Also run on pull requests when .md files are changed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install required packages
      run: |
        sudo apt-get update && \
        sudo apt-get install pandoc texlive-xetex -y

    - name: Convert Markdown files to PDF
      run: |
        mkdir -p output_pdf
        for file in *.md; do
          echo "Converting $file to PDF using xelatex"
          pandoc "$file" -o "output_pdf/${file%.md}.pdf" --pdf-engine=xelatex
        done

    - name: Upload PDF Files
      uses: actions/upload-artifact@v3
      with:
        name: PDFs
        path: output_pdf
