name: Convert Markdown to PDF

on:
  push:
    branches:
      - main    # Run when code is pushed to the main branch
  pull_request:
    branches:
      - main    # Also run on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # The environment the workflow runs in

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3    # Use the latest version of actions/checkout

    - name: Install wkhtmltopdf
      run: sudo apt-get install wkhtmltopdf -y  # Install wkhtmltopdf

    - name: List Files (Debugging Step)
      run: ls -R   # This step will help you verify the file structure in the runner

    - name: Convert Markdown files to PDF using wkhtmltopdf
      run: |
        mkdir -p output_pdf                # Create output directory
        for file in **/*.md; do
          # Convert each .md to PDF using wkhtmltopdf, assuming HTML conversion first
          markdown_file="${file%.md}.html"  # Convert .md to .html first using markdown
          markdown $file > $markdown_file
          wkhtmltopdf --enable-local-file-access "$markdown_file" "output_pdf/${file%.md}.pdf"
        done

    - name: Upload PDF Files
      uses: actions/upload-artifact@v3      # Upload the generated PDFs as artifacts
      with:
        name: PDFs
        path: output_pdf                   # Upload the generated PDFs as artifacts
