name: Convert Markdown to PDF

on:
  push:
    paths:
      - '**/*.md'  # Only run when .md files are changed
  pull_request:
    paths:
      - '**/*.md'  # Also run on pull requests when .md files are changed

jobs:
  build:
    runs-on: ubuntu-latest  # The environment the workflow runs in

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Use the latest version of actions/checkout

    - name: Install required packages
      run: |
        sudo apt-get update && \
        sudo apt-get install -y pandoc texlive-xetex  # Install pandoc and texlive

    - name: Convert Markdown files to PDF
      run: |
        mkdir -p output_pdf  # Create output directory for PDFs
        for file in *.md; do
          echo "Converting $file to PDF using xelatex"  # Log the file being processed
          pandoc "$file" -o "output_pdf/${file%.md}.pdf" --pdf-engine=xelatex  # Convert .md to .pdf

    - name: Debug: Check Filesystem and Cache Directories
      run: |
        echo "Checking system paths..."
        df -h       # Check mounted filesystems
        ls -al $HOME/.cache/pandoc || echo "Pandoc cache directory does not exist"
        ls -al /var/lib/apt/lists || echo "APT lists directory does not exist"

    - name: Cache Pandoc and APT lists
      uses: actions/cache@v4
      with:
        path: |
          $HOME/.cache/pandoc   # Pandoc cache directory (if exists)
          /var/lib/apt/lists     # Cache apt lists to speed up package installs (if exists)
        key: texlive-pandoc-${{ runner.os }}-${{ hashFiles('**/*.md') }}
        restore-keys: |
          texlive-pandoc-${{ runner.os }}-

    - name: Upload PDF Files
      uses: actions/upload-artifact@v4  # Upload the generated PDFs as artifacts
      with:
        name: PDFs
        path: output_pdf  # Upload the generated PDFs as artifacts
